---
- name: Create hello-world namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: hello-world

- name: Apply Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-world-deployment
        namespace: hello-world
        labels:
          app: hello-world
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: hello-world
        template:
          metadata:
            labels:
              app: hello-world
          spec:
            containers:
            - name: hello-world
              image: gcr.io/google-samples/hello-app:1.0

- name: Verify Pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: hello-world
  register: pod_status

- name: Debug Pod Status
  debug:
    var: pod_status
